# Generated by Django 4.0.4 on 2022-05-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_professor', models.CharField(max_length=50)),
                ('pagina_do_linkedin', models.CharField(max_length=150)),
                ('pagina_da_lusofona', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_projeto', models.CharField(max_length=50)),
                ('linguagem_de_programacao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_cadeira', models.CharField(max_length=50)),
                ('ano_da_cadeira', models.IntegerField(default=1)),
                ('semestre_da_cadeira', models.IntegerField(default=1)),
                ('link_da_pagina', models.CharField(max_length=150)),
                ('estrelas_da_cadeira', models.IntegerField(default=3)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor')),
            ],
        ),
    ]
