# Generated by Django 4.0.4 on 2022-05-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_cadeira_id_alter_professor_id_alter_projeto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='ects',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='professor',
            name='pagina_da_lusofona',
            field=models.CharField(default='https://www.ulusofona.pt/', max_length=150),
        ),
        migrations.AlterField(
            model_name='professor',
            name='pagina_do_linkedin',
            field=models.CharField(default='https://www.linkedin.com/login/pt', max_length=150),
        ),
    ]
