# Generated by Django 4.0.4 on 2022-05-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_cadeira_ects_alter_professor_pagina_da_lusofona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_da_pessoa', models.CharField(max_length=50)),
                ('pagina_do_linkedin', models.CharField(default='https://www.linkedin.com/login/pt', max_length=150)),
                ('pagina_da_lusofona', models.CharField(default='https://www.ulusofona.pt/', max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='linguagem_de_programacao',
        ),
        migrations.AddField(
            model_name='projeto',
            name='ano_de_realizacao_do_projeto',
            field=models.IntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='projeto',
            name='cadeira_do_projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao_do_projeto',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_da_competencia', models.CharField(max_length=50)),
                ('descricao_curta_da_competencia', models.CharField(max_length=200)),
                ('disciplina_onde_foi_trabalhada_a_competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira')),
                ('projeto_onde_foi_aplicada_a_competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projeto')),
            ],
        ),
    ]
