# Generated by Django 4.0.4 on 2022-05-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_pessoa_remove_projeto_linguagem_de_programacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem_do_projeto',
            field=models.ImageField(default=1, upload_to='static/portfolio/images'),
            preserve_default=False,
        ),
    ]
