# Generated by Django 4.0.4 on 2022-05-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_competencia_disciplina_onde_foi_trabalhada_a_competencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_da_escola', models.CharField(max_length=150)),
                ('curso_frequentado', models.CharField(max_length=50)),
                ('local_da_escola', models.CharField(max_length=50)),
                ('logotipo_da_escola', models.ImageField(upload_to='static/portfolio/images')),
                ('quantos_anos_estive', models.IntegerField(default=1)),
            ],
        ),
    ]
