# Generated by Django 4.0.4 on 2022-05-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='grau_de_ensino',
            field=models.IntegerField(default=0),
        ),
    ]
