# Generated by Django 4.0.4 on 2022-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_escola_grau_de_ensino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='curso_frequentado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
