# Generated by Django 4.0.4 on 2022-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_escola_curso_frequentado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='curso_frequentado',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escola',
            name='logotipo_da_escola',
            field=models.ImageField(upload_to='db-images'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem_do_projeto',
            field=models.ImageField(upload_to='db-images'),
        ),
    ]
