# Generated by Django 4.0.4 on 2022-05-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_escola_curso_frequentado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='logotipo_da_escola',
            field=models.ImageField(upload_to='db-images/images'),
        ),
    ]
