# Generated by Django 4.0.4 on 2022-05-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_escola_logotipo_da_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem_do_projeto',
            field=models.ImageField(upload_to='db-images/images'),
        ),
    ]
