# Generated by Django 4.0.4 on 2022-05-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_projeto_imagem_do_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='id_do_projeto',
            field=models.IntegerField(default=0),
        ),
    ]
