# Generated by Django 4.0.4 on 2022-05-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_projeto_id_do_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='id_do_projeto',
        ),
    ]
