# Generated by Django 4.0.4 on 2022-05-24 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_projeto_id_do_projeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='pagina_da_lusofona',
            new_name='pagina_do_github',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='projeto_onde_foi_aplicada_a_competencia',
        ),
        migrations.AddField(
            model_name='projeto',
            name='aptidao_utilizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.competencia'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='link_do_github',
            field=models.CharField(default='https://github.com/goncaloantunes22106935', max_length=100),
        ),
        migrations.AddField(
            model_name='projeto',
            name='link_do_youtube',
            field=models.CharField(default='https://www.youtube.com/', max_length=100),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias_usadas',
            field=models.CharField(default='Nenhuma tecnologia utilizada.', max_length=150),
        ),
    ]
