# Generated by Django 4.0.4 on 2022-05-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_rename_pagina_da_lusofona_pessoa_pagina_do_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('autor_da_publicacao', models.CharField(default='Gonçalo Antunes', max_length=50)),
                ('titulo_da_publicacao', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=700)),
                ('link_do_github', models.CharField(max_length=150)),
                ('foto_da_publicacao', models.ImageField(upload_to='db-images/images')),
            ],
        ),
    ]
