# Generated by Django 4.0.4 on 2022-05-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='autor_da_publicacao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='foto_da_publicacao',
            field=models.ImageField(blank=True, null=True, upload_to='db-images/images'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='link_do_github',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
