# Generated by Django 4.0.4 on 2022-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_publicacao_autor_da_publicacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_do_jogador', models.CharField(max_length=50)),
                ('pontuacao', models.IntegerField(default=0)),
            ],
        ),
    ]
