# Generated by Django 4.0.5 on 2022-06-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_jogador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='logotipo_da_escola',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='imagem_do_projeto',
        ),
        migrations.RemoveField(
            model_name='publicacao',
            name='foto_da_publicacao',
        ),
    ]
