# Generated by Django 4.0.5 on 2022-06-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_escola_logotipo_da_escola_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=50)),
                ('ano', models.IntegerField(default=2021)),
                ('titulo', models.CharField(max_length=50)),
                ('resumo', models.CharField(max_length=700)),
                ('relatorio', models.CharField(blank=True, max_length=100)),
                ('link_github', models.CharField(default='https://github.com/goncaloantunes22106935', max_length=150)),
                ('video_demonstrativo', models.CharField(default='https://www.youtube.com/', max_length=150)),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor')),
            ],
        ),
    ]
