# Generated by Django 4.0.5 on 2022-06-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_quizz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='pontuacao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
