# Generated by Django 4.0.5 on 2022-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_tecnologia_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='criador',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='descricao',
            field=models.CharField(default=1, max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='nome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='pagina',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
